# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossl < Formula
  desc "interactive CLI tool that helps to check and process the information of certificate and private key files, making it easy to apply the certificate to a web server"
  homepage "https://github.com/ghdwlsgur/gossl"
  version "1.4.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/gossl/releases/download/v1.4.4/gossl_1.4.4_Darwin_arm64.tar.gz"
      sha256 "3eeae1387d3264d5769ea6ce715338eb66786b06d78e1d00991d5693d281baed"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/gossl/releases/download/v1.4.4/gossl_1.4.4_Darwin_x86_64.tar.gz"
      sha256 "b49e9bf45a4d307e29974c28bee3da5d62809121ca2f1eea3a48aa5af9c57b6c"

      def install
        bin.install "gossl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/gossl/releases/download/v1.4.4/gossl_1.4.4_Linux_arm64.tar.gz"
      sha256 "4ca97037b46477eff47969f543b5c612da59eb9d03f2c68a130e90d39727e551"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/gossl/releases/download/v1.4.4/gossl_1.4.4_Linux_x86_64.tar.gz"
      sha256 "3f3dce5336df03e918d46dcf8061f9b2d99125a09f33f9751c09672679cbfeb3"

      def install
        bin.install "gossl"
      end
    end
  end
end
