# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossl < Formula
  desc "An interactive cli tool that easily binds HTTPS certificates and diagnoses whether certificates are applied with edge servers as proxy."
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/gossl/releases/download/v0.0.2/gossl_0.0.2_Darwin_arm64.tar.gz"
      sha256 "1a75c8511d5b6449e085e476dc28060878088acffaa13ce390afeea14f60ba1d"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/gossl/releases/download/v0.0.2/gossl_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "e77fc9f7066a4f4f317c0d4c75146024dc791fb8010314ddef98b6c211719cbc"

      def install
        bin.install "gossl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/gossl/releases/download/v0.0.2/gossl_0.0.2_Linux_arm64.tar.gz"
      sha256 "53604144ba438c786a1579aa940bd3be06791d72a4f3859101fe2763cf374e58"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/gossl/releases/download/v0.0.2/gossl_0.0.2_Linux_x86_64.tar.gz"
      sha256 "12739763234b7039f9e664107afa38a0f846f80500875ada5590c3dc65dc10a8"

      def install
        bin.install "gossl"
      end
    end
  end
end
