# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossl" do
  version "1.9.1"

  on_macos do
    on_arm do
      sha256 "0d059b9bc75f62c102e0da0d20cfd1f7b9f848ae69a362b236c37333d046b8bd"
      url "https://github.com/ghdwlsgur/gossl/releases/download/v#{version}/gossl_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "78d67e0ca79778c70e070bc4e9e1f30b209cf85563590d026b9b60fba6fe7c0e"
      url "https://github.com/ghdwlsgur/gossl/releases/download/v#{version}/gossl_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77cc4c76bb20c83225f529e1ea9bf1ede9c038054fc7c2ac8f1e10763044775c"
      url "https://github.com/ghdwlsgur/gossl/releases/download/v#{version}/gossl_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f758991213d2cfdb6845b7bf595c63915b381981e37d435db5f99542764b66b"
      url "https://github.com/ghdwlsgur/gossl/releases/download/v#{version}/gossl_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gossl"
  desc "Split, merge and inspect TLS certificate files, interactively or in a pipeline"
  homepage "https://github.com/ghdwlsgur/gossl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gossl"]
    end
  end

  # No zap stanza required
end
