# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossl" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gossl"]
    end
  end

  version "1.9.2"

  on_macos do
    on_arm do
      sha256 "78002af61601b536cf99f076533bc0a2c0477c38725c82049a93601a7e2f80bd"
      url "https://github.com/ghdwlsgur/gossl/releases/download/v#{version}/gossl_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "741d910f29abafed503134c79ec91a96886b6ade25236d78078b81f7c1aae87c"
      url "https://github.com/ghdwlsgur/gossl/releases/download/v#{version}/gossl_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "39f60273258d69b3e9b64d134e5708986e363696862c70c8f07802f9ffc21e7f"
      url "https://github.com/ghdwlsgur/gossl/releases/download/v#{version}/gossl_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "049a6d6f3aa26885489dbac6bbb418f6d834c075e40c5bc2422f0b1540d7fd6b"
      url "https://github.com/ghdwlsgur/gossl/releases/download/v#{version}/gossl_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gossl"
  desc "Split, merge and inspect TLS certificate files, interactively or in a pipeline"
  homepage "https://github.com/ghdwlsgur/gossl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossl"

  # No zap stanza required
end
